import './bootstrap';
import { initNavigation } from './Components/navigation';
import { initAdminNavigation } from './Components/admin-navigation';
import { initPublicNavigationSearch } from './Components/public-navigation-search';
import { initNewsletterForm } from './Components/newsletter-form';
import { initAdminCommandCenter } from './Components/admin-command-center';
import { initTheme } from './Components/theme';
import { initPortalNavigation } from './Components/portal-navigation';
import { initMotion } from './Components/motion';
import { initModals, initTabs } from './Components/ui';
import { initCareersPage } from './Pages/careers';
import { initContactPage } from './Pages/contact';
import { initPartnerHubPage } from './Pages/partner-hub';
import { initInsightsPage } from './Pages/insights';
import { initCommunityPage } from './Pages/community';
import { initInnovationLabPage } from './Pages/innovation-lab';
import { initIndustriesPage } from './Pages/industries';
import { initPortfolioPage } from './Pages/portfolio';
import { initProductsPage } from './Pages/products';
import { initSolutionsPage } from './Pages/solutions';
import { initLeadershipPage } from './Pages/leadership';
import { initHomepage } from './Pages/homepage';
import { initDesignSystemPage } from './Pages/design-system';
import { initInitializationPage } from './Pages/initialization';
import { initLoginPage } from './Pages/login';
import { initAiAssistantPage } from './Pages/ai-assistant';

document.addEventListener('DOMContentLoaded', () => {
    initInitializationPage();
    initLoginPage();
    initAiAssistantPage();
    initHomepage();
    initLeadershipPage();
    initSolutionsPage();
    initProductsPage();
    initIndustriesPage();
    initPortfolioPage();
    initInnovationLabPage();
    initCommunityPage();
    initInsightsPage();
    initCareersPage();
    initContactPage();
    initPartnerHubPage();
    initDesignSystemPage();
    initNavigation();
    initPublicNavigationSearch();
    initNewsletterForm();
    initAdminNavigation();
    initAdminCommandCenter();
    initPortalNavigation();
    initTheme();
    initMotion();
    initModals();
    initTabs();
});
