import './bootstrap';
import { initNavigation } from './components/navigation';
import { initModals, initTabs } from './components/ui';
import { initCareersPage } from './pages/careers';
import { initContactPage } from './pages/contact';
import { initPartnerHubPage } from './pages/partner-hub';
import { initInsightsPage } from './pages/insights';
import { initCommunityPage } from './pages/community';
import { initInnovationLabPage } from './pages/innovation-lab';
import { initIndustriesPage } from './pages/industries';
import { initPortfolioPage } from './pages/portfolio';
import { initProductsPage } from './pages/products';
import { initSolutionsPage } from './pages/solutions';
import { initLeadershipPage } from './pages/leadership';
import { initHomepage } from './pages/homepage';
import { initDesignSystemPage } from './pages/design-system';
import { initInitializationPage } from './pages/initialization';
import { initLoginPage } from './pages/login';

document.addEventListener('DOMContentLoaded', () => {
    initInitializationPage();
    initLoginPage();
    initHomepage();
    initLeadershipPage();
    initSolutionsPage();
    initProductsPage();
    initIndustriesPage();
    initPortfolioPage();
    initInnovationLabPage();
    initCommunityPage();
    initInsightsPage();
    initCareersPage();
    initContactPage();
    initPartnerHubPage();
    initDesignSystemPage();
    initNavigation();
    initModals();
    initTabs();
});
