<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Admin Catalog Modules
    |--------------------------------------------------------------------------
    | Generic CRUD admin workspaces for content catalog modules.
    */

    'modules' => [
        'solutions' => [
            'label' => 'Services',
            'singular' => 'Service',
            'description' => 'Manage enterprise solution offerings on the public Solutions hub.',
            'repository' => \App\Repositories\SolutionOfferingRepository::class,
            'categories_config' => 'cyra.solutions.categories',
            'public_route' => 'solutions.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'spark'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'capabilities', 'label' => 'Capabilities', 'type' => 'list', 'rows' => 4],
                ['name' => 'outcomes', 'label' => 'Outcomes', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'industries' => [
            'label' => 'Industries',
            'singular' => 'Industry',
            'description' => 'Manage industry verticals and sector expertise pages.',
            'repository' => \App\Repositories\IndustryVerticalRepository::class,
            'categories_config' => 'cyra.industries.categories',
            'public_route' => 'industries.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'building'],
                ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'challenges', 'label' => 'Challenges', 'type' => 'list', 'rows' => 4],
                ['name' => 'capabilities', 'label' => 'Capabilities', 'type' => 'list', 'rows' => 4],
                ['name' => 'compliance', 'label' => 'Compliance', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'products' => [
            'label' => 'Products',
            'singular' => 'Product',
            'description' => 'Manage Cyra-Tech product offerings and platform capabilities.',
            'repository' => \App\Repositories\ProductOfferingRepository::class,
            'categories_config' => 'cyra.products.categories',
            'public_route' => 'products.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'badge', 'label' => 'Badge', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'cube'],
                ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'features', 'label' => 'Features', 'type' => 'list', 'rows' => 4],
                ['name' => 'use_cases', 'label' => 'Use Cases', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'innovation-lab' => [
            'label' => 'Innovation Lab',
            'singular' => 'Initiative',
            'description' => 'Manage innovation lab initiatives and venture programs.',
            'repository' => \App\Repositories\InnovationInitiativeRepository::class,
            'categories_config' => 'cyra.innovation_lab.categories',
            'public_route' => 'innovation-lab.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'badge', 'label' => 'Badge', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'light-bulb'],
                ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'timeline', 'label' => 'Timeline', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'focus_areas', 'label' => 'Focus Areas', 'type' => 'list', 'rows' => 4],
                ['name' => 'deliverables', 'label' => 'Deliverables', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'portfolio' => [
            'label' => 'Portfolio',
            'singular' => 'Project',
            'description' => 'Manage portfolio projects and case studies.',
            'repository' => \App\Repositories\PortfolioProjectRepository::class,
            'categories_config' => 'cyra.portfolio.categories',
            'public_route' => 'portfolio.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'client_name', 'label' => 'Client Name', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'collection'],
                ['name' => 'duration', 'label' => 'Duration', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'services', 'label' => 'Services', 'type' => 'list', 'rows' => 4],
                ['name' => 'outcomes', 'label' => 'Outcomes', 'type' => 'list', 'rows' => 4],
                ['name' => 'metrics', 'label' => 'Metrics', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'leadership' => [
            'label' => 'Leadership',
            'singular' => 'Leader',
            'description' => 'Manage executive leadership profiles.',
            'repository' => \App\Repositories\LeadershipProfileRepository::class,
            'categories_config' => null,
            'public_route' => null,
            'title_field' => 'name',
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'title', 'label' => 'Role Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'tier', 'label' => 'Tier', 'type' => 'select', 'required' => true, 'grid' => 'half', 'options' => [
                    'executive' => 'Executive',
                    'extended' => 'Extended Leadership',
                ]],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'grid' => 'half'],
                ['name' => 'linkedin_url', 'label' => 'LinkedIn URL', 'type' => 'url', 'grid' => 'half'],
                ['name' => 'bio', 'label' => 'Bio', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'focus_areas', 'label' => 'Focus Areas', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'careers' => [
            'label' => 'Careers',
            'singular' => 'Opening',
            'description' => 'Manage career openings and job listings.',
            'repository' => \App\Repositories\CareerOpeningRepository::class,
            'categories_config' => 'cyra.careers.categories',
            'public_route' => 'careers.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'department', 'label' => 'Department', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'location', 'label' => 'Location', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'work_type', 'label' => 'Work Type', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'experience_level', 'label' => 'Experience Level', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'badge', 'label' => 'Badge', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'career'],
                ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'responsibilities', 'label' => 'Responsibilities', 'type' => 'list', 'rows' => 4],
                ['name' => 'requirements', 'label' => 'Requirements', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'community' => [
            'label' => 'Community',
            'singular' => 'Program',
            'description' => 'Manage community programs and engagement initiatives.',
            'repository' => \App\Repositories\CommunityProgramRepository::class,
            'categories_config' => 'cyra.community.categories',
            'public_route' => 'community.show',
            'title_field' => 'title',
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'category', 'label' => 'Category', 'type' => 'category', 'required' => true, 'grid' => 'half'],
                ['name' => 'badge', 'label' => 'Badge', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'icon', 'label' => 'Icon Key', 'type' => 'text', 'grid' => 'half', 'default' => 'community'],
                ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'text', 'required' => true, 'grid' => 'full'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'rows' => 5],
                ['name' => 'membership', 'label' => 'Membership', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'schedule', 'label' => 'Schedule', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'benefits', 'label' => 'Benefits', 'type' => 'list', 'rows' => 4],
                ['name' => 'activities', 'label' => 'Activities', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
        'team-members' => [
            'label' => 'Team Members',
            'singular' => 'Team Member',
            'description' => 'Manage the public team directory.',
            'repository' => \App\Repositories\TeamMemberRepository::class,
            'categories_config' => null,
            'public_route' => null,
            'title_field' => 'name',
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'grid' => 'half'],
                ['name' => 'title', 'label' => 'Role Title', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'department', 'label' => 'Department', 'type' => 'text', 'required' => true, 'grid' => 'half'],
                ['name' => 'location', 'label' => 'Location', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'work_type', 'label' => 'Work Type', 'type' => 'text', 'grid' => 'half'],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'grid' => 'half'],
                ['name' => 'linkedin_url', 'label' => 'LinkedIn URL', 'type' => 'url', 'grid' => 'half'],
                ['name' => 'bio', 'label' => 'Bio', 'type' => 'textarea', 'rows' => 5, 'default' => ''],
                ['name' => 'skills', 'label' => 'Skills', 'type' => 'list', 'rows' => 4],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'grid' => 'half', 'default' => 0],
            ],
        ],
    ],
];
